services:
  frontend:
    container_name: slurm-proxy
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - /Users/areynolds/.ssh:/Users/areynolds/.ssh:ro
      - /home/areynolds/.ssh:/home/areynolds/.ssh:ro
    ports:
      - "5001:5001"
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - SLURM_PROXY_WIREGUARD_PRIVATE_PROD_KEY=${SLURM_PROXY_WIREGUARD_PRIVATE_PROD_KEY}
      - SLURM_PROXY_WIREGUARD_PRESHARED_PROD_KEY=${SLURM_PROXY_WIREGUARD_PRESHARED_PROD_KEY}
      - SLURM_PROXY_WIREGUARD_PRIVATE_DEV_KEY=${SLURM_PROXY_WIREGUARD_PRIVATE_DEV_KEY}
      - SLURM_PROXY_WIREGUARD_PRESHARED_DEV_KEY=${SLURM_PROXY_WIREGUARD_PRESHARED_DEV_KEY}